
- hosts: localhost
  become: true
  tasks:
  - name: check whether postman exists
    stat: 
      path: /usr/local/Postman
    register: postman

  - name: Download Postman
    get_url:
      url: https://dl.pstmn.io/download/latest/linux64
      dest: /tmp/Postman.tar.gz
      mode: "u=r,g=,o="
    when: not postman.stat.exists
    register: postman_download

  - name: Unarchive postman
    unarchive:
      src=/tmp/Postman.tar.gz
      dest=/usr/local/Postman
    when: postman_download


