---
- hosts: localhost
  become: true
  pre_tasks:
  - name: Add deadsnakes ppa repo key
    apt_key: 
      id: 6A755776
      url: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x6A755776
      state: present

  - apt_repository:
      repo: "ppa:deadsnakes/ppa"
      state: present

  tasks:
  - name: Install python packages and a few things required for building pip packages
    action: apt pkg={{item}} state=present
    with_items:
      - build-essential 
      - libssl-dev 
      - python3.6
      - python3.6-dev 
      - python3-pip 

  - name: Install pipenv
    action: pip name={{item}} version=3.6 state=present
    with_items:
      - pipenv
