---
- hosts: localhost
  become: true
  pre_tasks:
  - name: Add deadsnakes ppa repo key
    apt_key: 
      id: 6A755776
      url: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x6A755776
      state: present

  - apt_repository:
      repo: "ppa:deadsnakes/ppa"
      state: present

  tasks:
  - name: Install python packages and a few things required for building pip packages
    action: apt pkg={{item}} state=present update_cache=true
    with_items:
      - build-essential 
      - libssl-dev 
      - python3.6
      - python3.6-dev 
      - python3-pip 

  #can't use the ansible pip module because the version of ansible is python 2 and therefore
  #uses python2's pip, which means flake8 doesn't work at all and other packages install into the
  #wrong python version
  - name: Install python packages
    command: pip3 install {{item}} --upgrade
    become: true
    with_items:
      - flake8
      - jupyter
      - numpy
      - pandas
      - pipenv
      - scipy
    args:
      warn: false
    register: python_package_install
    failed_when: >
      python_package_install.rc != 0
    changed_when: "python_package_install.stdout == 'Successfully installed'"
